version: 2.1

orbs:
  queue: eddiewebb/queue@1.4.2

jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
  test:
    docker:
      - image: circleci/python:3.8
    steps:
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'

  staging_deploy:
    docker:
      - image: circleci/python:3.8
    steps:
      - queue/until_front_of_line:
          only-on-branch: master
          time: '10'
      - run: echo "This job will not overlap"
      - deploy:
          name: Staging Deployment
          command: |
            echo 'DEPLOYING STAG!!!'

workflows:
  simple_workflow:
    jobs:
      - build
      - test
      - wait_for_approve:
          type: approval
          requires:
            - build
      - deploy:
          requires:
            - wait_for_approve
