version: 2.1
jobs:
  basic_docker_build:
    machine: true
    steps:
      - attach_workspace:
          at: /home/circleci/project
      - run:
          name: Build Docker image
          command: docker build -t Direside/example-circleci-pipeline .

  # If you'd like to use docker build inside of a docker executor, you can do this too using the `setup_remote_docker` step.
  basic_docker_build_remote_docker:
    docker:
      - image: circleci/golang:1.13-alpine
    steps:
      - attach_workspace:
          at: /home/circleci/project
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker image
          command: docker build -t Direside/example-circleci-pipeline .

workflows:
  docker_builds:
    jobs:
      - basic_docker_build
      - basic_docker_build_remote_docker